#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : m17n-lib
Version  : 1.8.0
Release  : 2
URL      : http://download.savannah.gnu.org/releases/m17n/m17n-lib-1.8.0.tar.gz
Source0  : http://download.savannah.gnu.org/releases/m17n/m17n-lib-1.8.0.tar.gz
Summary  : Core API suport of the m17n library.
Group    : Development/Tools
License  : LGPL-2.1
Requires: m17n-lib-bin = %{version}-%{release}
Requires: m17n-lib-lib = %{version}-%{release}
Requires: m17n-lib-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : fontconfig-dev
BuildRequires : freetype-dev
BuildRequires : fribidi-dev
BuildRequires : libX11-dev
BuildRequires : libXft-dev
BuildRequires : libXt-dev
BuildRequires : libgd-dev
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libthai)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xft)
BuildRequires : xorgproto-dev

%description
2012, 2013, 2014
National Institute of Advanced Industrial Science and Technology (AIST)
Registration Number H15PRO112
See the end for copying conditions.

%package bin
Summary: bin components for the m17n-lib package.
Group: Binaries
Requires: m17n-lib-license = %{version}-%{release}

%description bin
bin components for the m17n-lib package.


%package dev
Summary: dev components for the m17n-lib package.
Group: Development
Requires: m17n-lib-lib = %{version}-%{release}
Requires: m17n-lib-bin = %{version}-%{release}
Provides: m17n-lib-devel = %{version}-%{release}
Requires: m17n-lib = %{version}-%{release}

%description dev
dev components for the m17n-lib package.


%package lib
Summary: lib components for the m17n-lib package.
Group: Libraries
Requires: m17n-lib-license = %{version}-%{release}

%description lib
lib components for the m17n-lib package.


%package license
Summary: license components for the m17n-lib package.
Group: Default

%description license
license components for the m17n-lib package.


%prep
%setup -q -n m17n-lib-1.8.0
cd %{_builddir}/m17n-lib-1.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604357617
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check

%install
export SOURCE_DATE_EPOCH=1604357617
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/m17n-lib
cp %{_builddir}/m17n-lib-1.8.0/COPYING %{buildroot}/usr/share/package-licenses/m17n-lib/caeb68c46fa36651acf592771d09de7937926bb3
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/m17n-conv
/usr/bin/m17n-date
/usr/bin/m17n-dump
/usr/bin/m17n-edit
/usr/bin/m17n-view

%files dev
%defattr(-,root,root,-)
/usr/include/m17n-X.h
/usr/include/m17n-core.h
/usr/include/m17n-flt.h
/usr/include/m17n-gui.h
/usr/include/m17n-misc.h
/usr/include/m17n.h
/usr/lib64/libm17n-core.so
/usr/lib64/libm17n-flt.so
/usr/lib64/libm17n-gui.so
/usr/lib64/libm17n.so
/usr/lib64/pkgconfig/m17n-core.pc
/usr/lib64/pkgconfig/m17n-flt.pc
/usr/lib64/pkgconfig/m17n-gui.pc
/usr/lib64/pkgconfig/m17n-shell.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libm17n-core.so.0
/usr/lib64/libm17n-core.so.0.4.2
/usr/lib64/libm17n-flt.so.0
/usr/lib64/libm17n-flt.so.0.4.2
/usr/lib64/libm17n-gui.so.0
/usr/lib64/libm17n-gui.so.0.4.2
/usr/lib64/libm17n.so.0
/usr/lib64/libm17n.so.0.4.2
/usr/lib64/m17n/1.0/libm17n-X.so
/usr/lib64/m17n/1.0/libm17n-gd.so
/usr/lib64/m17n/1.0/libmimx-anthy.so
/usr/lib64/m17n/1.0/libmimx-ispell.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/m17n-lib/caeb68c46fa36651acf592771d09de7937926bb3
