#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : m17n-lib
Version  : 1.8.4
Release  : 4
URL      : https://download.savannah.gnu.org/releases/m17n/m17n-lib-1.8.4.tar.gz
Source0  : https://download.savannah.gnu.org/releases/m17n/m17n-lib-1.8.4.tar.gz
Summary  : GUI API suport of the m17n library.
Group    : Development/Tools
License  : LGPL-2.1
Requires: m17n-lib-bin = %{version}-%{release}
Requires: m17n-lib-lib = %{version}-%{release}
Requires: m17n-lib-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : fribidi-dev
BuildRequires : libX11-dev
BuildRequires : libXft-dev
BuildRequires : libXt-dev
BuildRequires : libgd-dev
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libthai)
BuildRequires : pkgconfig(xft)
BuildRequires : xorgproto-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
2012, 2013, 2014
National Institute of Advanced Industrial Science and Technology (AIST)
Registration Number H15PRO112
See the end for copying conditions.

%package bin
Summary: bin components for the m17n-lib package.
Group: Binaries
Requires: m17n-lib-license = %{version}-%{release}

%description bin
bin components for the m17n-lib package.


%package dev
Summary: dev components for the m17n-lib package.
Group: Development
Requires: m17n-lib-lib = %{version}-%{release}
Requires: m17n-lib-bin = %{version}-%{release}
Provides: m17n-lib-devel = %{version}-%{release}
Requires: m17n-lib = %{version}-%{release}

%description dev
dev components for the m17n-lib package.


%package lib
Summary: lib components for the m17n-lib package.
Group: Libraries
Requires: m17n-lib-license = %{version}-%{release}

%description lib
lib components for the m17n-lib package.


%package license
Summary: license components for the m17n-lib package.
Group: Default

%description license
license components for the m17n-lib package.


%prep
%setup -q -n m17n-lib-1.8.4
cd %{_builddir}/m17n-lib-1.8.4
pushd ..
cp -a m17n-lib-1.8.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719975466
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check
cd ../buildavx2;
make check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719975466
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/m17n-lib
cp %{_builddir}/m17n-lib-%{version}/COPYING %{buildroot}/usr/share/package-licenses/m17n-lib/caeb68c46fa36651acf592771d09de7937926bb3 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/m17n-conv
/V3/usr/bin/m17n-date
/V3/usr/bin/m17n-dump
/V3/usr/bin/m17n-edit
/V3/usr/bin/m17n-view
/usr/bin/m17n-conv
/usr/bin/m17n-date
/usr/bin/m17n-dump
/usr/bin/m17n-edit
/usr/bin/m17n-view

%files dev
%defattr(-,root,root,-)
/usr/include/m17n-X.h
/usr/include/m17n-core.h
/usr/include/m17n-flt.h
/usr/include/m17n-gui.h
/usr/include/m17n-misc.h
/usr/include/m17n.h
/usr/lib64/libm17n-core.so
/usr/lib64/libm17n-flt.so
/usr/lib64/libm17n-gui.so
/usr/lib64/libm17n.so
/usr/lib64/pkgconfig/m17n-core.pc
/usr/lib64/pkgconfig/m17n-flt.pc
/usr/lib64/pkgconfig/m17n-gui.pc
/usr/lib64/pkgconfig/m17n-shell.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libm17n-core.so.0.4.2
/V3/usr/lib64/libm17n-flt.so.0.4.2
/V3/usr/lib64/libm17n-gui.so.0.4.2
/V3/usr/lib64/libm17n.so.0.4.2
/V3/usr/lib64/m17n/1.0/libm17n-X.so
/V3/usr/lib64/m17n/1.0/libm17n-gd.so
/V3/usr/lib64/m17n/1.0/libmimx-anthy.so
/V3/usr/lib64/m17n/1.0/libmimx-ispell.so
/usr/lib64/libm17n-core.so.0
/usr/lib64/libm17n-core.so.0.4.2
/usr/lib64/libm17n-flt.so.0
/usr/lib64/libm17n-flt.so.0.4.2
/usr/lib64/libm17n-gui.so.0
/usr/lib64/libm17n-gui.so.0.4.2
/usr/lib64/libm17n.so.0
/usr/lib64/libm17n.so.0.4.2
/usr/lib64/m17n/1.0/libm17n-X.so
/usr/lib64/m17n/1.0/libm17n-gd.so
/usr/lib64/m17n/1.0/libmimx-anthy.so
/usr/lib64/m17n/1.0/libmimx-ispell.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/m17n-lib/caeb68c46fa36651acf592771d09de7937926bb3
